const sfw = {
  'a': 'Anime & Manga',
  'c': 'Anime/Cute',
  'g': 'Technology',
  'k': 'Weapons',
  'm': 'Mecha',
  'o': 'Auto',
  'p': 'Photography',
  'v': 'Video Games',
  'vg': 'Video Games Generals',
  'vr': 'Retro Games',
  'w': 'Anime/Wallpapers',
  'vip': 'Very Important Posts',
  'qa': 'Question & Answer',
  'cm': 'Cute/Male',
  '3': '3DCG',
  'adv': 'Advice',
  'an': 'Animals & Nature',
  'asp': 'Alternative Sports & Wrestling',
  'biz': 'Business & Finance',
  'cgl': 'Cosplay & EGL',
  'ck': 'Food & Cooking',
  'co': 'Comics & Cartoons',
  'diy': 'Do It Yourself',
  'fa': 'Fashion',
  'fit': 'Fitness',
  'gd': 'Graphic Design',
  'his': 'History & Humanities',
  'int': 'International',
  'jp': 'Otaku Culture',
  'lit': 'Literature',
  'mlp': 'Pony',
  'mu': 'Music',
  'n': 'Transportation',
  'news': 'Current News',
  'out': 'Outdoors',
  'po': 'Papercraft & Origami',
  'pol': 'Politically Incorrect',
  'qsts': 'Quests',
  'sci': 'Science & Math',
  'sp': 'Sports',
  'tg': 'Traditional Games',
  'toy': 'Toys',
  'trv': 'Travel',
  'tv': 'Television & Film',
  'vp': 'Pokémon',
  'wsg': 'Worksafe GIF',
  'wsr': 'Worksafe Requests',
  'x': 'Paranormal'
}

module.exports = sfw
